import {
  AboutTheCompany,
  Auth,
  Basket,
  Blog,
  ChangePassword,
  Comparison,
  ts,
  Delivery,
  Editing,
  FeaturedProducts,
  Home,
  MyAddress,
  MyOrders,
  NotFound,
  Ordering,
  PasswordRecovery,
  Payment,
  PrivacyPolicy,
  ProductCard,
  ProductCatalog,
  Profile,
  QuestionAndAnswer,
  Return,
  Reviews,
  SearchResults,
  Stock,
} from "../pages";

export const routes = [
  { path: "/", element: <Home /> },
  { path: "/about", element: <AboutTheCompany /> },
  { path: "/auth", element: <Auth /> },
  { path: "/basket", element: <Basket /> },
  { path: "/blog", element: <Blog /> },
  { path: "/change-password", element: <ChangePassword /> },
  { path: "/comparison", element: <Comparison /> },
  { path: "/ts", element: <ts /> },
  { path: "/delivery", element: <Delivery /> },
  { path: "/editing", element: <Editing /> },
  { path: "/featured-products", element: <FeaturedProducts /> },
  { path: "/my-address", element: <MyAddress /> },
  { path: "/my-orders", element: <MyOrders /> },
  { path: "/ordering", element: <Ordering /> },
  { path: "/password-recovery", element: <PasswordRecovery /> },
  { path: "/payment", element: <Payment /> },
  { path: "/privacy-policy", element: <PrivacyPolicy /> },
  { path: "/product-card", element: <ProductCard /> },
  { path: "/product-catalog", element: <ProductCatalog /> },
  { path: "/profile", element: <Profile /> },
  { path: "/q-and-a", element: <QuestionAndAnswer /> },
  { path: "/return", element: <Return /> },
  { path: "/reviews", element: <Reviews /> },
  { path: "/search-results", element: <SearchResults /> },
  { path: "/stock", element: <Stock /> },
  { path: "*", element: <NotFound /> },
];
